### PR TITLE
Make v0.0.24

### PR DESCRIPTION
**Pull request by marwaalarab**
Hi Venexia, 
I changed the file type of analysis ready dataset to csv.gz and updated readme, changelog and project yaml accordingly. 
Thanks, 
Marwa

### CODE REVIEW

**Comment by remlapmot** [comment]
Very nice, but remember that the version of **readr** in r-docker is old, so I fixed the `file` argument back to `path` to work with this old version.

**Comment by marwaalarab** [comment]
@remlapmot Thanks Tom! I didn't know that :)

**Comment by remlapmot** [comment]
(I made the same fix to the previous PR, so was fresh in my mind.)

**Review by venexia — APPROVED** [review]
Great job, thanks @marwaalarab and @remlapmot !

**Pull request merged**
