### PR TITLE
Make it default for all exposed individuals to be in the analysis regardless of case/control status

### PR DESCRIPTION
**Pull request by venexia**
Sorry for all the PRs @remlapmot !

### CODE REVIEW

**Comment by venexia** [comment]
P.S. @remlapmot If this is approved, please can you merge so that @josephignace can start using it. I will be out of the office next week and don't want to hold anyone up!

**Review by remlapmot — APPROVED** [review]
Looks good to me.

I just fixed one typo.

Also I think your version of RStudio (well pandoc/rmarkdown/knitr really) might be older than mine - which is my guess for why you get the extra spaces after some bullet points when rendering the *README.md* from *README.Rmd*.

**Comment by remlapmot** [comment]
@josephignace - just letting you know that this is merged.

**Comment by josephignace** [comment]
@remlapmot Thanks Tom.

**Pull request merged**
