### PR TITLE
Save analysis ready dataset and add option to run analysis

### PR DESCRIPTION
**Pull request by venexia**
- Specify analysis ready data set as output in YAML
- Add option to not run analysis (i.e., just save analysis ready dataset and stop)

### CODE REVIEW

**Comment by remlapmot** [comment]
Hope ok, I did 2 minor amends:

- The version of **readr** in r-docker pre-dates the changing of the `path` argument to `file`. If/when **readr** is updated in r-docker you'll have to remember to edit this argument name back.
- On line 46 of *README.Rmd* the line number needs to be the line of *cox-ipw.R* which has `opt_parser <- OptionParser(...)` on. You must have had this correct initially when you rendered the Rmd file, but then added another line to *cox-ipw.R* (or something like that).

My query is - what's the reason for now saving the empty dataset/s on lines 392-394 of *cox-ipw.R*? Seems a bit redundant to be saving these.

**Comment by venexia** [comment]
Hi @remlapmot - thank you for that fix, I saw the test failed but didn't have time to get back to it yesterday. 

I am saving the empty datasets because I am not aware of a way to optionally specify outputs in the YAML and avoid the output not found error. The outputs 'analysis_ready' and 'estimates' are only sometimes saved, depending on the options specified for 'save_analysis_ready' and 'run_analysis'.  If they are not created then I am saving an empty dataset so that there is always some output to be found. Do you know of a better solution?

**Comment by remlapmot** [comment]
> I am saving the empty datasets because I am not aware of a way to optionally specify outputs in the YAML and avoid the output not found error. The outputs 'analysis_ready' and 'estimates' are only sometimes saved, depending on the options specified for 'save_analysis_ready' and 'run_analysis'. If they are not created then I am saving an empty dataset so that there is always some output to be found. Do you know of a better solution?

Oh yes, that's fine then. I don't know of a better solution (other than just documenting that you need to specify the extra YAML when the dataset is saved). 

So now you are always saving the dataset I think we need to add the extra YAML to the instructions in the README that you have added to the *project.yaml*, which I'll try to do now.

**Comment by venexia** [comment]
Thanks @remlapmot, are you happy for this to be merged now?

**Comment by remlapmot** [comment]
Yes, that's great - thanks Venexia

**Pull request merged**
